// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import model "github.com/mdstella/true-tickets-challenge/model"

// MetricDao is an autogenerated mock type for the MetricDao type
type MetricDao struct {
	mock.Mock
}

// GetMetricSumByKey provides a mock function with given fields: key
func (_m *MetricDao) GetMetricSumByKey(key string) ([]model.MetricDto, error) {
	ret := _m.Called(key)

	var r0 []model.MetricDto
	if rf, ok := ret.Get(0).(func(string) []model.MetricDto); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.MetricDto)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StoreMetric provides a mock function with given fields: key, value
func (_m *MetricDao) StoreMetric(key string, value int) error {
	ret := _m.Called(key, value)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int) error); ok {
		r0 = rf(key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
